# Generated by Django 4.2.6 on 2023-11-10 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='customuser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('roll_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('hostel_location', models.CharField(choices=[('MBH1', 'MBH1'), ('MBH2', 'MBH2'), ('MLH', 'MLH'), ('LH1', 'LH1'), ('LH2', 'LH2'), ('LH3', 'LH3'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('PG', 'PG')], max_length=4)),
                ('event_registration_count', models.IntegerField(default=0)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.today)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('isClubAdmin', models.BooleanField(default=False)),
                ('admin_position', models.CharField(blank=True, max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=200)),
                ('club_fa', models.CharField(max_length=200)),
                ('club_opening_balance', models.FloatField()),
                ('club_balance', models.FloatField(default=0)),
                ('club_logo', models.ImageField(blank=True, upload_to='images/club_logo/')),
                ('club_admin', models.ForeignKey(default='B210021CS', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', events.models.CustomAutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_venue', models.CharField(max_length=300)),
                ('event_budget', models.FloatField(default=0, null=True)),
                ('event_cost', models.FloatField(default=0, null=True)),
                ('event_regfee', models.FloatField()),
                ('event_image', models.ImageField(blank=True, upload_to='images/event_images/')),
                ('event_students', models.IntegerField(default=0)),
                ('event_profit', models.FloatField(default=0)),
                ('event_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.club')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_id', events.models.CustomAutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student_id', 'event_id')},
            },
        ),
    ]
