# Generated by Django 4.2.6 on 2023-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_customuser_date_joined_alter_event_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_profit',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
    ]
