# Generated by Django 4.2.6 on 2023-10-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_event_profit_alter_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_profit',
            field=models.FloatField(default=0),
        ),
    ]
