# Generated by Django 4.2.6 on 2023-10-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_balance',
            field=models.FloatField(null=True),
        ),
    ]
