# Generated by Django 4.2.6 on 2023-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_club_club_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_balance',
            field=models.FloatField(default=0),
        ),
    ]
