# Generated by Django 4.2.6 on 2023-11-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_club_club_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_budget',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_cost',
            field=models.FloatField(default=0, null=True),
        ),
    ]
