# Generated by Django 4.2.6 on 2023-11-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_budget_alter_event_event_cost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student_id', 'event_id')},
        ),
    ]
