# Generated by Django 4.2.6 on 2023-11-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_registration_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
    ]
