# Generated by Django 4.2.6 on 2023-11-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_registration_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student_id', 'event_id')},
        ),
    ]
